version: '3'
services:
  app:
    build: './backend'
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV='prod'
    restart: always
    links:
      - postgresql
  postgresql:
    build: './postgresql'
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
    ports:
      - '5434:5432'
    restart: always
    environment:
      - POSTGRES_PASSWORD='postgres'